index:
    path: /
    controller: App\Controller\DashboardController::index
database:
    path: /components
    controller: App\Controller\ComponentsController::index
projects:
    path: /projects
    controller: App\Controller\ProjectsController::index
